<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Klabukov Erik</Authors>
    <Description>Simple modular system implementation</Description>
    <PackageTags>depenedncy injecton; modules;</PackageTags>
    <VersionPrefix>0.0.1</VersionPrefix>
    <RepositoryUrl>https://github.com/AMEST/Skidbladnir</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.7.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
  </ItemGroup>

</Project>
