<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Klabukov Erik</Authors>
    <Product />
    <Description>GridFS implementation of IStorage abstraction for store files</Description>
    <PackageTags>storage; files; gridfs</PackageTags>
    <RepositoryUrl>https://github.com/AMEST/Skidbladnir</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver.GridFS" Version="2.30.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Skidbladnir.Storage.Abstractions\Skidbladnir.Storage.Abstractions.csproj" />
  </ItemGroup>

</Project>
